spring:
  cloud:
    aws:
      sns:
        endpoint: ${SNS_ENDPOINT:https://sns.eu-west-2.amazonaws.com}
      region:
        static: ${AWS_REGION:eu-west-2}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:ACCESS_KEY}
        secret-key: ${AWS_SECRET_ACCESS_KEY:SECRET_KEY}

sns_topic_arn: ${SNS_TOPIC_ARN:arn:aws:sns:eu-west-2:000000000000:exchange-order-created}
