aws:
  sns:
    endpoint: http://localhost:4566
    region: eu-west-2
  sqs:
    endpoint: http://localhost:4566
    region: eu-west-2

spring:
  config:
    activate:
      on-profile: integration
  cloud:
      aws:
        sns:
          endpoint: https://sns.us-east-1.amazonaws.com  
        region:
          static: us-east-1
        credentials:
          access-key: YOUR_ACCESS_KEY_HERE
          secret-key: YOUR_SECRET_KEY_HERE

sns_topic_arn: "arn:aws:sns:eu-west-2:000000000000:exchange-order-created"

